name: Update-Deps
on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  update-deps:
    runs-on: ubuntu-latest
    name: Update dependency
    steps:      
      - name: Get latest commit id
        run: git rev-parse HEAD