name: Update-Deps
on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  update-deps:
    runs-on: ubuntu-latest
    name: Update dependency
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: updating backend shared
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          cd backend
          go get golang.org/x/tools/gopls@v0.6.4
          git status
          git add .
          git commit -m "Test"
          git push origin develop
