name: Update-Deps
on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  update-deps:
    runs-on: ubuntu-latest
    name: Update dependency
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12